language: python

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - google-chrome-stable

sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./bootstrap.sh
  - ./start-servers.sh
  - sleep 5
install: pip install pytest selenium
script: python setup.py develop && py.test test
sudo: false
dist: trusty
